#!/usr/bin/env bash
#
# lib/build.sh - Assemble build context, generate Containerfile, and run podman build
#

set -euo pipefail

# Assembles build context and executes derived bootc container build and validation.
# Globals read:
#   BASE_IMAGE_RESOLVED
#   RPMS_DIR
#   TEST_SCRIPT
#   TEST_ARGS (array)
#   DERIVED_TAG
#   CALLER_TAG_SPECIFIED (boolean)
#   KEEP_IMAGE (boolean)
# Globals set:
#   DERIVED_IMAGE_TAG
#   DERIVED_IMAGE_ID
run_build_and_validation() {
  local context_dir
  context_dir="$(mktemp -d -t bootc-test-context.XXXXXX)"

  # Track image IDs for ownership-safe cleanup
  local pre_existing_id=""
  local created_image_id=""

  # Setup exit trap for cleanup of context and disposable images
  # shellcheck disable=SC2317
  cleanup() {
    local exit_code=$?
    log_info "Cleaning up temporary build context: ${context_dir}"
    rm -rf "${context_dir}"

    if [ "${KEEP_IMAGE}" = "true" ]; then
      if [ -n "${created_image_id}" ]; then
        log_info "Preserving derived image as requested (--keep-image): ${DERIVED_TAG} (${created_image_id})"
      fi
      exit "${exit_code}"
    fi

    # Ownership-safe image cleanup
    if [ -n "${created_image_id}" ]; then
      if [ "${CALLER_TAG_SPECIFIED}" = "false" ]; then
        # Tag was generated by harness exclusively for this disposable run
        log_info "Removing disposable harness test image: ${DERIVED_TAG}"
        podman rmi -f "${DERIVED_TAG}" >/dev/null 2>&1 || true
      else
        # Caller provided a custom tag. Never remove an image that predated this run.
        if [ -n "${pre_existing_id}" ] && [ "${pre_existing_id}" = "${created_image_id}" ]; then
          log_info "Image ${DERIVED_TAG} (${created_image_id}) predated harness invocation; leaving intact."
        else
          log_info "Removing disposable derived test image: ${DERIVED_TAG}"
          podman rmi -f "${DERIVED_TAG}" >/dev/null 2>&1 || true
        fi
      fi
    fi

    exit "${exit_code}"
  }
  trap cleanup EXIT

  # 1. Verify caller RPMs
  [ -d "${RPMS_DIR}" ] || die "RPM directory not found: ${RPMS_DIR}"

  shopt -s nullglob
  local rpm_files=("${RPMS_DIR}"/*.rpm)
  shopt -u nullglob

  if [ "${#rpm_files[@]}" -eq 0 ]; then
    die "No .rpm files found in directory: ${RPMS_DIR}"
  fi

  log_info "Staging ${#rpm_files[@]} caller RPM(s) from ${RPMS_DIR} into build context..."
  mkdir -p "${context_dir}/rpms"
  cp -L "${rpm_files[@]}" "${context_dir}/rpms/"

  # 2. Stage test script if provided
  local has_test_script=false
  if [ -n "${TEST_SCRIPT:-}" ]; then
    [ -f "${TEST_SCRIPT}" ] || die "Test script not found: ${TEST_SCRIPT}"
    has_test_script=true
    mkdir -p "${context_dir}/test-assets"
    cp "${TEST_SCRIPT}" "${context_dir}/test-assets/test-script"
    chmod +x "${context_dir}/test-assets/test-script"

    # Generate runner script with argv-safe passthrough
    {
      echo '#!/usr/bin/env bash'
      echo 'set -euo pipefail'
      echo 'args=()'
      for arg in "${TEST_ARGS[@]}"; do
        printf 'args+=(%q)\n' "${arg}"
      done
      cat <<'RUNNER_EXEC'
if [ -x /tmp/test-assets/test-script ]; then
  exec /tmp/test-assets/test-script "${args[@]}"
else
  exec /bin/bash /tmp/test-assets/test-script "${args[@]}"
fi
RUNNER_EXEC
    } > "${context_dir}/test-assets/run-test.sh"
    chmod +x "${context_dir}/test-assets/run-test.sh"
    log_info "Staged caller test script: ${TEST_SCRIPT} with ${#TEST_ARGS[@]} argument(s)"
  fi

  # 3. Generate Containerfile
  {
    cat <<'DOCKERFILE_HEAD'
ARG BASE_IMAGE

FROM scratch AS ctx
COPY rpms /rpms
DOCKERFILE_HEAD

    if [ "${has_test_script}" = "true" ]; then
      echo 'COPY test-assets /test-assets'
    fi

    cat <<'DOCKERFILE_BASE'

FROM ${BASE_IMAGE}

# Install caller RPMs using ephemeral bind and cache/tmpfs mounts
RUN --mount=type=bind,from=ctx,source=/rpms,target=/tmp/rpms,ro \
    --mount=type=cache,dst=/var/cache \
    --mount=type=cache,dst=/var/log \
    --mount=type=tmpfs,dst=/run \
    --mount=type=tmpfs,dst=/tmp \
    dnf5 install -y /tmp/rpms/*.rpm

DOCKERFILE_BASE

    if [ "${has_test_script}" = "true" ]; then
      cat <<'DOCKERFILE_TEST'
# Execute caller validation script inside tmpfs work environment
RUN --mount=type=bind,from=ctx,source=/test-assets,target=/tmp/test-assets,ro \
    --mount=type=tmpfs,target=/tmp/work \
    /bin/bash /tmp/test-assets/run-test.sh

DOCKERFILE_TEST
    fi

    cat <<'DOCKERFILE_LINT'
# Mandatory static structural bootc validation
RUN bootc container lint
DOCKERFILE_LINT
  } > "${context_dir}/Containerfile"

  # 4. Check for pre-existing image matching tag
  pre_existing_id="$(podman images -q --no-trunc "${DERIVED_TAG}" 2>/dev/null || true)"

  log_info "Building derived bootc image from: ${BASE_IMAGE_RESOLVED}"
  log_info "Target tag: ${DERIVED_TAG}"

  podman build \
    --build-arg BASE_IMAGE="${BASE_IMAGE_RESOLVED}" \
    -f "${context_dir}/Containerfile" \
    -t "${DERIVED_TAG}" \
    "${context_dir}"

  # 5. Capture new image ID
  created_image_id="$(podman images -q --no-trunc "${DERIVED_TAG}" 2>/dev/null || true)"
  if [ -z "${created_image_id}" ]; then
    log_warn "Could not resolve image ID for built tag ${DERIVED_TAG}"
  else
    log_info "Derived image successfully created with ID: ${created_image_id}"
  fi

  # shellcheck disable=SC2034
  DERIVED_IMAGE_TAG="${DERIVED_TAG}"
  # shellcheck disable=SC2034
  DERIVED_IMAGE_ID="${created_image_id:-none}"
}
